/**
 * services/content-snapshot.ts
 *
 * Read-only access to the bundled Firebase snapshot (server/src/data/site-snapshot.ts,
 * generated by `npm run snapshot`). firebase.ts uses this when a live read fails.
 *
 * Only the public content nodes are in the snapshot. Anything else (calendar,
 * audit, logs, notifications…) returns `undefined` so the caller keeps its
 * normal error behaviour for private data.
 */
import { SITE_SNAPSHOT } from '../data/site-snapshot';

export const SNAPSHOT_NODES = new Set(['siteContent', 'blog', 'profiles', 'nav', 'calcConfig']);

export const snapshotMeta = SITE_SNAPSHOT.meta;

/**
 * Look up a logical path ('siteContent/home', 'blog/post1', 'nav/members') in
 * the snapshot.
 *
 * @returns a deep copy of the value, `null` if the node is covered by the
 *          snapshot but the path doesn't exist, or `undefined` if the path is
 *          outside the snapshot entirely.
 */
export function snapshotGet<T = unknown>(logicalPath: string): T | null | undefined {
  const segments = logicalPath.replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
  if (segments.length === 0 || !SNAPSHOT_NODES.has(segments[0])) return undefined;

  let node: unknown = SITE_SNAPSHOT;
  for (const key of segments) {
    if (node === null || typeof node !== 'object') return null;
    node = (node as Record<string, unknown>)[key];
    if (node === undefined) return null;
  }
  return node === null ? null : (structuredClone(node) as T);
}
