/**
 * schema/snapshot — hardcoded fallback copy of the Firebase /public content.
 *
 * SiteService and CalculatorConfigService read from here ONLY when the live
 * Realtime Database errors, times out, or returns nothing. The data lives in
 * ./data.ts, which is generated by `npm run snapshot` (scripts/snapshot-content.mjs)
 * and refreshed automatically on every production build.
 *
 * Every accessor returns a deep copy so callers can never mutate the snapshot.
 */
import type { BlogPost, Profile, SiteSection } from '@schema/models';
import { SITE_SNAPSHOT } from './data';
import type { RawSiteSnapshot, SnapshotMeta } from './types';

export type { RawSiteSnapshot, SnapshotMeta } from './types';

const snap: RawSiteSnapshot = SITE_SNAPSHOT;

const clone = <T>(v: T): T => (v == null ? v : structuredClone(v));

/** When / where the bundled snapshot came from. */
export const SNAPSHOT_META: SnapshotMeta = snap.meta;

/** One siteContent section ('home' | 'aboutUs' | 'areasOfLaw' | 'faq' | 'pricing'). */
export function snapshotSection(section: string): SiteSection | null {
  const s = snap.siteContent?.[section];
  return s ? clone(s as SiteSection) : null;
}

/** Raw blog node keyed by post id (same shape as Firebase /public/blog). */
export function snapshotBlog(): Record<string, Omit<BlogPost, 'id'>> {
  return clone((snap.blog ?? {}) as Record<string, Omit<BlogPost, 'id'>>);
}

/** Raw profiles node (Firebase may store it as an object or an array). */
export function snapshotProfiles(): Profile[] {
  const raw = snap.profiles;
  if (!raw) return [];
  const list = Array.isArray(raw) ? raw : Object.values(raw);
  return clone(list.filter((p): p is Profile => !!p && typeof p === 'object' && 'id' in p));
}

/** nav/members ordering list, if present. */
export function snapshotNavMembers(): { value: string; order: number }[] | null {
  const members = (snap.nav as { members?: unknown } | null)?.members;
  return Array.isArray(members) ? clone(members as { value: string; order: number }[]) : null;
}

/** Calculator config node, or null if it was never saved to Firebase. */
export function snapshotCalcConfig<T = unknown>(): T | null {
  return snap.calcConfig ? clone(snap.calcConfig as T) : null;
}
